# Generated by Django 3.1.3 on 2020-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0002_bloodbank_bloodbankadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='BloodPackets',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='BloodPackets',
            field=models.ManyToManyField(to='website_pages.BloodPacket'),
        ),
    ]
