# Generated by Django 3.1.3 on 2020-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0003_auto_20201104_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpacket',
            name='Blood_bank',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='website_pages.bloodbank'),
        ),
    ]
