# Generated by Django 3.1.3 on 2020-11-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0005_auto_20201104_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=70)),
                ('campName', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('district', models.CharField(max_length=70)),
                ('contactNo', models.CharField(max_length=15)),
                ('organizedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_pages.bloodbank')),
            ],
        ),
    ]
