# Generated by Django 3.1.3 on 2020-11-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0007_auto_20201106_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpacket',
            name='Blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_pages.bloodbank'),
        ),
    ]
