# Generated by Django 3.1.3 on 2020-11-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_pages', '0008_auto_20201106_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='BloodBankAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
