# Generated by Django 3.1.3 on 2020-11-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0009_auto_20201106_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='BloodPackets',
            field=models.ManyToManyField(blank=True, to='website_pages.BloodPacket'),
        ),
    ]
