# Generated by Django 3.1.3 on 2020-11-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0010_auto_20201109_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpacket',
            name='Blood_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_pages.bloodbank'),
        ),
    ]
