# Generated by Django 3.1.3 on 2020-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0011_auto_20201109_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpacket',
            name='price',
            field=models.FloatField(default=500.0),
        ),
    ]
