# Generated by Django 3.1.3 on 2020-11-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_pages', '0012_bloodpacket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packetID', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('bloodBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_pages.bloodbank')),
                ('boughtBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
