# Generated by Django 3.1.2 on 2020-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=12)),
                ('is_blood_bank_admin', models.BooleanField(default=False)),
                ('is_donor_or_receiver', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_group', models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-')], max_length=3)),
                ('number_of_donations', models.IntegerField(default=0)),
                ('data_share', models.BooleanField(default=True)),
            ],
        ),
    ]
