# Generated by Django 3.1.2 on 2020-10-26 15:49
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_admin_user(apps, schema_editor):
    User = apps.get_model('user', 'User')
    u = User.objects.create(first_name='vips', contact_number='1234567890', dob='2000-12-12', city='ABC',
                            blood_group='1', data_share=True, username='vips', email='a@a.com')
    u.password = make_password('vips')
    u.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user)
    ]
