name: Print Secret

on:
  push:
    branches:
      - master

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret value
        id: secret-check
        run: |
          if [[ "${{ secrets.DEPLOYMENT_KEY }}" == "value is secret" ]]; then
            echo "matched=true" >> $GITHUB_ENV
          else
            echo "matched=false" >> $GITHUB_ENV
          fi

      - name: Output result
        run: |
          echo "Secret match result: ${{ env.matched }}"
